on:
  push:
    branches:
      - beta-version
name: \@ashuk203/bare-node-proj
jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      did-create-release: ${{ steps.release.outputs.release_created }}
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: node
          release-as: 0.1.0
          package-name: release-please-action
          default-branch: beta-version

      # - uses: actions/checkout@v2

      #   if: ${{ steps.release.outputs.release_created }}
      # - uses: ./.github/workflows/npm-publish.yml
      #   if: ${{ steps.release.outputs.release_created }}

  npm-publish:
    needs: release-please
    if: needs.release-please.outputs.did-create-release
    uses: ./.github/workflows/npm-publish.yml
    secrets: inherit
