on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main
name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      did-create-release: ${{ steps.release.outputs.release_created }}
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: node
          package-name: release-please-action

      # - uses: actions/checkout@v2

      #   if: ${{ steps.release.outputs.release_created }}
      # - uses: ./.github/workflows/npm-publish.yml
      #   if: ${{ steps.release.outputs.release_created }}

  npm-publish:
    needs: release-please
    if: needs.release-please.outputs.did-create-release
    uses: ./.github/workflows/npm-publish.yml
    secrets: inherit
