on: 
  workflow_dispatch:

jobs:
  test-python:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.extract-version.outputs.version }}
    steps:
      - name: Test array iterate
        run: |
          for i in c,3 \
              e,5; 
                do IFS=","; 
                set -- $i; 
                echo $1 and $2; 
          done


