on:
  workflow_dispatch:

name: Auto push test

jobs:
  push-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR base branch
        uses: actions/checkout@v3
        with:
          repository: ashutosh-ukey/bare-node-proj-dist
          token: ${{ secrets.ASHU_PAT }}
          path: temp-dest-repo

      - name: Generate random number
        run: |
          echo $((1 + $RANDOM % 1000)) > temp-dest-repo/rand-num.txt

      - name: Import GPG key
        id: import-gpg
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.ASHU_GPG_PRIVATE }}
          passphrase: ${{ secrets.ASHU_GPG_PASSPHRASE }}
          git_config_global: true
          git_user_signingkey: true
          git_commit_gpgsign: true

      - name: Publish to openapi repository
        id: push_directory
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.ASHU_PAT }}
        with:
          user-email: ${{ steps.import-gpg.outputs.email }}
          user-name: ${{ steps.import-gpg.outputs.name }}

          source-directory: temp-dest-repo
          destination-repository-username: ashutosh-ukey
          destination-repository-name: bare-node-proj-dist
          commit-message: Testing repo push action
          target-branch: test-master-1